# Generated by Django 6.0.7 on 2026-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='state',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=24),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly')], default='MONTHLY', max_length=12),
        ),
    ]
