# Generated by Django 6.0.7 on 2026-07-29 21:56

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_idempotencykey_state_alter_plan_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(default=billing.models.make_key, max_length=256, unique=True),
        ),
    ]
