# Generated by Django 6.0.7 on 2026-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('base_fee__gt', 0)), name='prevent_negative_base_fee'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('unit_fee__gt', 0)), name='prevent_negative_unit_fee'),
        ),
    ]
