# Generated by Django 6.0.7 on 2026-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_prevent_negative_base_fee_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='prevent_negative_base_fee',
        ),
        migrations.RemoveConstraint(
            model_name='plan',
            name='prevent_negative_unit_fee',
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('base_fee__gte', 0)), name='prevent_negative_base_fee'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('unit_fee__gte', 0)), name='prevent_negative_unit_fee'),
        ),
    ]
