# Generated by Django 6.0.7 on 2026-08-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_plan_prevent_negative_base_fee_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_end__gt', models.F('current_period_start'))), name='prevent_zero_length_period'),
        ),
    ]
