# Generated by Django 6.0.7 on 2026-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscription_prevent_zero_length_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('OPEN', 'Open'), ('VOID', 'Void')], max_length=12),
        ),
    ]
