# Generated by Django 6.0.7 on 2026-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_period',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VOID'), _negated=True), fields=('tenant', 'period_start', 'period_end'), name='unique_invoice_period'),
        ),
    ]
