# Generated by Django 6.0.7 on 2026-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoice_unique_invoice_period_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('tenant',), name='unique_open_invoice_per_tenant'),
        ),
    ]
